"use client"

import { Header } from "@/components/header"
import { Footer } from "@/components/footer"
import { EmotionProvider } from "@/contexts/emotion-context"

export default function TermsPage() {
  return (
    <EmotionProvider>
      <main className="relative min-h-screen bg-background text-foreground overflow-x-hidden pt-24">
        <div className="fixed inset-0 pointer-events-none z-0">
          <div className="absolute top-0 right-1/4 w-full max-w-lg h-[500px] bg-glow-blue/22 rounded-full" />
        </div>
        <Header />
        <div className="max-w-3xl mx-auto px-6 py-20 relative z-10">
          <div className="mb-12">
            <p className="text-muted-foreground text-sm tracking-[0.3em] uppercase mb-4">Legal</p>
            <h1 className="text-3xl md:text-4xl font-semibold tracking-tight mb-4">Terms of Service</h1>
            <p className="text-muted-foreground text-lg">Last updated: June 2026</p>
          </div>
          
          <div className="space-y-10 text-foreground/70 leading-relaxed text-base md:text-lg">
            <section className="space-y-4">
              <h2 className="text-2xl font-medium tracking-tight text-foreground">1. Agreement to Terms</h2>
              <p>
                By accessing or using Orwyn, you agree to be bound by these Terms of Service. If you do not agree, please do not use the service.
              </p>
              <p>
                Orwyn is intended for users who are 13 years of age or older. If you are under 18, please use Orwyn only with the involvement of a parent or guardian. By using Orwyn, you confirm that you meet these age requirements. We do not knowingly collect personal data from children under 13. If we discover that a child under 13 has provided personal data, we will delete it immediately.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-medium tracking-tight text-foreground">2. Disclaimer</h2>
              <p>
                <strong className="text-foreground/90 font-medium">Orwyn is not a replacement for professional mental health support.</strong> Our application is designed to be a safe space for journaling and self-reflection. Orwyn is an artificial intelligence system, not a human being or a licensed mental health professional. All responses are generated by AI. If you are experiencing a mental health crisis, please seek professional help or contact emergency services immediately.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-medium tracking-tight text-foreground">3. User Responsibilities</h2>
              <p>
                You are responsible for safeguarding the password and device that you use to access Orwyn. We encrypt your data, but protecting access to your device ensures your privacy is fully maintained.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-medium tracking-tight text-foreground">4. Intellectual Property</h2>
              <p>
                The application, its original features, and design remain the exclusive property of Onestbond Technologies Private Limited. Your personal entries and data belong entirely to you.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-medium tracking-tight text-foreground">5. Changes to Terms</h2>
              <p>
                We reserve the right to modify these terms at any time. If we make material changes, we will notify you within the app.
              </p>
            </section>

            <section className="space-y-4">
              <h2 className="text-2xl font-medium tracking-tight text-foreground">6. Governing Law</h2>
              <p>
                These Terms of Service are governed by and construed in accordance with the laws of India. 
                Any disputes arising from these terms shall be subject to the exclusive jurisdiction of 
                the courts in India. If you are accessing Orwyn from outside India, you are responsible 
                for compliance with local laws.
              </p>
            </section>
          </div>
        </div>
        <div className="mt-20">
          <Footer hideCta={true} />
        </div>
      </main>
    </EmotionProvider>
  )
}
